version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nvd-severity
    container_name: nvd-severity
    env_file:
      - .env
    volumes:
      - .:/nvd_severity